language: php

cache:
  directories:
    - vendor

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpcs
    - vendor/bin/phpunit
