language: php

cache:
  directories:
    - vendor

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4

before_script: composer update $COMPOSER_FLAGS
script:
    - vendor/bin/phpcs
    - vendor/bin/phpunit
